name: arryt
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.51+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  adaptive_dialog: ^1.8.0+1
  animated_snack_bar: ^0.3.0
  app_settings: ^5.1.1
  auto_route: ^7.8.4
  auto_size_text: ^3.0.0
  awesome_notifications: ^0.8.2
  awesome_notifications_core: ^0.8.0
  awesome_notifications_fcm: ^0.8.0
  badges: ^3.0.3
  cached_network_image: ^3.2.3
  chat_bubbles: ^1.3.1
  chat_package: ^1.0.0
  country_icons: ^2.0.2
  cryptlib_2_0: ^0.0.1
  cupertino_icons: ^1.0.2
  currency_formatter: ^2.0.0
  currency_text_input_formatter: ^2.1.8
  data_table_2: ^2.3.7
  device_info_plus: ^9.0.1
  dio: ^5.3.3
  dio_http2_adapter: ^2.3.1+1
  disable_battery_optimization: ^1.1.0+1
  easy_refresh: ^3.0.4+2
  equatable: ^2.0.5
  expandable: ^5.0.1
  firebase_analytics: ^10.0.1
  firebase_core: ^2.0.0
  firebase_crashlytics: ^3.0.7
  firebase_dynamic_links: ^5.0.11
  firebase_performance: ^0.9.0+1
  firebase_remote_config: ^3.0.1
  flutter:
    sdk: flutter
  flutter_awesome_buttons: ^1.1.0
  flutter_background_service: ^2.4.6
  flutter_background_service_android: ^3.0.3
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  flutter_inappwebview: ^5.8.0
  flutter_keyboard_visibility: ^5.4.0
  flutter_local_notifications: ^11.0.1
  flutter_localizations:
    sdk: flutter
  flutter_phone_direct_caller: ^2.1.1
  flutter_riverpod: ^2.4.6
  flutter_services_binding: null
  flutter_svg: ^1.1.5
  fluttertoast: ^8.1.1
  formz: ^0.4.0
  freezed_annotation: ^2.4.1
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get_it: ^7.6.4
  google_fonts: ^4.0.4
  graphql: 5.1.2-beta.4
  graphql_flutter: 5.1.1-beta.4
  group_button: ^5.2.2
  grouped_list: ^5.1.2
  hex: ^0.2.0
  http: ^0.13.5
  http_parser: ^4.0.2
  hydrated_bloc: ^9.1.0
  icons_launcher: ^2.0.5
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.1
  json_annotation: ^4.8.1
  keframe: ^3.0.0
  load_switch: ^1.2.0
  loader_overlay: ^2.1.0
  loading_overlay: ^0.3.0
  location: 5.0.0-dev.8
  map_launcher: ^2.4.0
  mat_month_picker_dialog: ^1.1.1
  modal_bottom_sheet: 3.0.0-pre
  month_year_picker: ^0.2.0+3
  objectbox: ^2.3.1
  objectbox_flutter_libs: ^2.3.1
  package_info_plus: ^4.0.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  persistent_bottom_nav_bar: ^5.0.2
  pin_code_fields: ^7.4.0
  provider: ^6.0.3
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  responsive_grid: ^2.1.0
  riverpod_annotation: ^2.3.1
  rounded_loading_button: ^2.1.0
  sms_autofill: ^2.2.0
  syncfusion_flutter_core: ^20.3.61
  syncfusion_flutter_datepicker: ^20.3.61
  tab_indicator_styler: ^2.0.0
  top_snackbar_flutter: ^2.1.1
  upgrader: ^8.1.0
  url_launcher: ^6.1.7
  webview_flutter: ^3.0.4
  workmanager: ^0.5.2

# dependency_overrides:
#   graphql:
#     git:
#       url: https://github.com/maximilianmaihoefner/graphql-flutter
#       path: packages/graphql
#       ref: graphql-transport-ws
dependency_overrides:
  web_socket_channel: 2.2.0
  intl: ^0.17.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  objectbox_generator: ^2.3.1
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.3.4

icons_launcher:
  image_path: "assets/icons/android/ic_launcher_xxxhdpi.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
