name: arryt
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.56+57

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  action_slider: ^0.8.0-beta.2
  adaptive_dialog: ^2.2.1+2
  animated_snack_bar: ^0.4.0
  animated_toggle_switch: ^0.8.0
  app_settings: ^5.1.1
  auto_route: ^9.2.2
  auto_size_text: ^3.0.0
  badges: ^3.0.3
  cached_network_image: ^3.2.3
  chatview: ^2.2.0
  country_icons: ^3.0.0
  cryptlib_2_0: ^0.0.1
  cupertino_icons: ^1.0.2
  currency_formatter: ^2.0.0
  currency_text_input_formatter: ^2.1.8
  data_table_2: ^2.3.7
  device_info_plus: ^10.1.2
  dio: ^5.4.1
  dio_http2_adapter: ^2.5.0
  disable_battery_optimization: ^1.1.0+1
  easy_refresh: ^3.3.2+4
  equatable: ^2.0.5
  expandable: ^5.0.1
  firebase_analytics: ^11.3.2
  firebase_core: ^3.5.0
  firebase_crashlytics: ^4.1.2
  firebase_messaging: ^15.1.2
  firebase_performance: ^0.10.0+7
  firebase_remote_config: ^5.1.2
  flutter:
    sdk: flutter
  flutter_awesome_buttons: ^1.1.0
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.7
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.20.5
  flutter_inappwebview: ^6.1.0+1
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^17.2.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  flutter_services_binding: null
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.1.1
  formz: ^0.7.0
  freezed_annotation: ^2.4.1
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  get_it: ^8.0.0
  google_fonts: ^6.2.1
  graphql: ^5.2.0-beta.9
  graphql_flutter: ^5.2.0-beta.7
  group_button: ^5.3.4
  grouped_list: ^6.0.0
  hex: ^0.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.2
  http_parser: ^4.0.2
  hydrated_bloc: ^9.1.0
  icons_launcher: ^3.0.0
  intl: ^0.17.0
  intl_phone_number_input:
    git:
      url: https://github.com/Shahidbangash/intl_phone_number_input.git
      ref: develop
  json_annotation: ^4.8.1
  keframe: ^3.0.0
  load_switch: ^2.1.0
  loader_overlay: ^4.0.2+1
  loading_overlay: ^0.3.0
  location: ^6.0.2
  map_launcher: ^3.5.0
  modal_bottom_sheet: ^3.0.0
  month_year_picker: ^0.4.0+1
  objectbox: ^4.0.2
  objectbox_flutter_libs: ^4.0.2
  package_info_plus: ^8.0.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  persistent_bottom_nav_bar: ^6.2.1
  pin_code_fields: ^8.0.1
  provider: ^6.0.3
  qr_flutter: ^4.0.0
  responsive_grid: ^2.1.0
  riverpod_annotation: ^2.3.1
  rounded_loading_button_plus: ^3.0.1
  sms_autofill: ^2.2.0
  store_locator: ^1.0.0
  syncfusion_flutter_core: ^27.1.48
  syncfusion_flutter_datepicker: ^27.1.48
  tab_indicator_styler: ^2.0.0
  top_snackbar_flutter: ^3.1.0
  upgrader: ^11.1.0
  url_launcher: ^6.3.0
  webview_flutter: ^4.9.0
  win32: ^5.5.4
  win32_registry: ^1.1.5
  workmanager: ^0.5.2

# dependency_overrides:
#   graphql:
#     git:
#       url: https://github.com/maximilianmaihoefner/graphql-flutter
#       path: packages/graphql
#       ref: graphql-transport-ws
dependency_overrides:
  # web_socket_channel: 2.2.0
  intl: ^0.17.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.2.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  objectbox_generator: ^4.0.2
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.3.4

icons_launcher:
  image_path: "assets/icons/android/ic_launcher_xxxhdpi.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
